=== Newtr/University-HTML-CSS-/Lr11/3.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Goroda">
<xs:complexType>
<xs:sequence>
<xs:element name="Minsk" type="xs:string"/>
<xs:element name="Brest" type="xs:string"/>
<xs:element name="Grodno" type="xs:string"/>
<xs:element name="Size" type="xs:string"/>
<xs:element name="People" type="xs:string"/>
<xs:element name="Rate" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== Newtr/University-HTML-CSS-/Lr11/3.xml
<?xml version="1.0" encoding="UTF8"?>
<Goroda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="3.xsd">
<Minsk>
<Size>Большой</Size>
<People>Много</People>
<Rate>10/10</Rate>
</Minsk>
<Brest>
<Size>Меньше</Size>
<People>Не так много как в Минске</People>
<Rate>8/10</Rate>
</Brest>
<Grodno>
<Size>Я не знаю</Size>
<People>Так же как и в Бресте</People>
<Rate>7/10</Rate>
</Grodno>
</Goroda>
